Vanessa/favorites fix
andreisarebi/civic-app pull request #24
Opened 2018-09-01 05:29 UTC by vahurtad

- fixed lost changes from last PR
- fixed conflicts
- adding Favorites UI

2018-09-01 15:04 UTC, gmferland commented
Yarn lock should not be deleted! Unless you want to have a conversation about using npm instead

2018-09-01 15:05 UTC, gmferland requested changes

2018-09-01 15:05 UTC, gmferland commented on src/candidate/redux/candidates.js
> +export const getCandidate = (state, id) =>(state[CANDIDATE_NAMESPACE][id])
This seems dubious

2018-09-04 19:53 UTC, cgalbiati commented
I think this still has duplicated commits (and maybe some that do not belong).  @gmferland I'm guessing that the deletion was a merge conflict issue, and not an attempt to stop using yarn

2018-09-04 20:13 UTC, gmferland commented
Yeah, I actually would love to get rid of yarn. I think the latest version of npm is much better. But that's a convo for a different day

2018-09-06 01:31 UTC, vahurtad commented
Hi guys, I think I have the correct changes done now with no conflicts on my end.

2018-09-06 02:24 UTC, gmferland approved these changes

2018-09-06 04:39 UTC, marcaaron approved these changes

2018-09-06 23:17 UTC, cgalbiati approved these changes

2018-09-07 01:58 UTC, merged